### ISSUE TITLE
Latest update doesn't work

### ISSUE THREAD

**Issue by SweDRak** [shirsig/aurae#10]
Hi,

I got all other addons disabled but only the bars shows up, not on the debuff. The version before worked fine except for my hunter!

Thanks

**Comment by shirsig** [comment]
>but only the bars shows up, not on the debuff

what?

**Comment by SweDRak** [comment]
The unitframe number doesnt work, only the bars does was what I was trying to say!

**Comment by shirsig** [comment]
This addon doesn't have unitframe numbers. https://forum.elysium-project.org/index.php?showtopic=24606

**Comment by SweDRak** [comment]
I'm talking about those images what they do and it doesn't work for me in the latest update but it seems to do for everyone else, at the sametime the earlier version works so it's really strange...

I guess it's an unknown problem from my side that you have no idea about lol

**Comment by shirsig** [comment]
The link is not the same addon.

**Comment by SweDRak** [comment]
Dear god, ok let's try the right link this time! Thank anyways :)
