### ISSUE TITLE
Rogues and Ruthlessness

### ISSUE THREAD

**Issue by Voidmenull** [shirsig/aurae#11]
the spell http://db.vanillagaming.org/?spell=14161

does trigger the UNIT_COMBAT (COMBO variable becomes to 1 point) event and therefor you get wrong timers(if proc) for Rupture and Kidney Shot :/

im not sure how to solv this...prob. add UNIT_COMBAT() in the spellhook function instead on event...

**Comment by shirsig** [comment]
Yeah, I've done this for my new version of aurae. However, if you use combat log events there probably isn't a simple solution.

**Comment by shirsig** [comment]
Well, I guess you could set it where the entry in "pending" is created. For other player's spells it won't work anyway and I guess all combo point spells are direct casts so this would probably work.

Still, there would almost certainly be some bad corner cases.

**Comment by Voidmenull** [comment]
works so far, can be closed if you fixed it in the main addon :)
