### ISSUE TITLE
Freezing Trap and DR

### ISSUE THREAD

**Issue by Voidmenull** [shirsig/aurae#12]
the DR calculation for Freezing Trap doesnt work

DR_CLASS = { ["Freezing Trap"] = 5, - has the wrong name in it, the effects name is Freezing Trap Effect

DR_CLASS = { ["Freezing Trap Effect"] = 5, does the job :)

**Comment by shirsig** [comment]
Oh, actually I can just remove that because I can't detect that anymore anyway without the combat log tracking, but good find :)
