### ISSUE TITLE
Multiple targets, same spells

### ISSUE THREAD

**Issue by allenj12** [shirsig/aurae#17]
when you have multiple targets with the same spell the latest one is the only one being tracked. Also if you have multiple spell on multiple targets at once even if you kill the mob associated with a spell it will not go away unless you kill the entire group you are currently fighting.

**Comment by shirsig** [comment]
The tracking limitation is only for pve and only if the targets have the same name, level and gender - and it cannot really be prevented except by making other concessions, e.g., in correct refreshing.

Also, in pve there are some limitations to removing timers. Removing on kill will only work at lvl 60 and only on your current target. The workaround is that they are removed when you leave combat. There is no way to improve this, again, except with concessions in other areas.

The reason for these issues is that in pve the name of a unit is not unique and there is no other way to identify them (except in some cases level and gender which i use as much as possible) so if you, e.g., get a combat log event like "x fades from Boar" you don't know which Boar it faded from or even if it was yours or another player's so you can't just remove the bar.
