### ISSUE TITLE
Shadowburn?

### ISSUE THREAD

**Issue by Monteo** [shirsig/aurae#18]
["Shadowburn"] = true,

	["Shadowburn"] = {
		ICON = 'Spell_Shadow_ScourgeBuild',
		DURATION = {5},
	},

and the effect of interest Shadow Vulnerability		
http://db.vanillagaming.org/?spell=17803

**Comment by shirsig** [comment]
I removed many effects including this when changing the focus to cc and generally effects which are useful to track off-target. To track stuff like this I would use https://forum.elysium-project.org/topic/25081-addon-debufftimers/
