### ISSUE TITLE
Removal of spells?

### ISSUE THREAD

**Issue by Larsy93** [shirsig/aurae#19]
Used this to track my Flameshock, is this no longer possible?

I know Debufftimers exist but thats not a bar.

**Comment by shirsig** [comment]
It only tracks ccs now. For other spells i would recommend https://forum.elysium-project.org/index.php?showtopic=25081 (https://github.com/Voidmenull/DebuffTimers/blob/master/DebuffTimers.lua).

**Comment by Larsy93** [comment]
Any chance you could upload the latest version before you took out the spell tracking? I understand if its too much hassle or if u dont have the files

**Comment by shirsig** [comment]
You'll have to go through the commits yourself to find the right one: https://github.com/shirsig/ccwatch/commits/master
Don't know when it was removed, been removing spells periodically for a while.

**Comment by Larsy93** [comment]
Ok got it, a question while we are at it, what is the Arcanist option and what does it do? Dont think its explained somewhere

**Comment by shirsig** [comment]
set bonus of the arcanist set (increased poly duration)

**Comment by shirsig** [comment]
gonna add automatic detection at some point (this is a leftover from the original CCWatch) either way, it only has an effect in pve anyway.

**Comment by shirsig** [comment]
hm, it seems the arcanist set has no polymorph related bonus :/ maybe it was for the -10 resistance bonus, but still doubt that would increase the duration by 15. Maybe I'll just remove it.

**Comment by Larsy93** [comment]
Ok, gotcha & what was the reason for removing the Dot tracking instead of just making it and option what dots/CCs u want to see? Addon memory usage?

**Comment by shirsig** [comment]
There are some issues with tracking debuffs which can have multiple instances on the same target which ccs don't have.

**Comment by Larsy93** [comment]
Ok, Still your tracker was pretty much the best one around. I really like bars instead of the icons. Will miss it alot...

**Comment by shirsig** [comment]
think you can change dotimer's appearance to bars

**Comment by Larsy93** [comment]
The DebuffTimer fork addon? Pretty sure its on the icons only.

**Comment by shirsig** [comment]
No, this old vanilla addon: http://www.vanilla-addons.com/dls/dotimer/. It has similar mechanics to mine. It's not useful for cc tracking because it doesn't have dr, pvp duration etc. but it is optimized for dots in a way that this never was.

On a different note, thanks to removing dots i was now able to eliminate the delay in pve too in most cases.

**Comment by Larsy93** [comment]
Ohh yes but that addon only works for warlock/priest/druid/hunter. So still alot of classes left out that your addon handled pretty much perfectly atleast in my book.

**Comment by Larsy93** [comment]
Voidmenull Said he wont bring back bara to his debbufftimer addon so I guess this is Lost :/

**Comment by Larsy93** [comment]
bars*
