### ISSUE TITLE
Lua error with rogue

### ISSUE THREAD

**Issue by NibelheimGG** [shirsig/aurae#20]
hello im getting a lua error and sometimes i cant see the CCs in PVP, here screenshot https://gyazo.com/0536cb0c8dfee087c8416d2efb9d9aef

**Comment by shirsig** [comment]
can you try if it's fixed now?

**Comment by NibelheimGG** [comment]
i keep getting the error and sometimes i lose the timer tracker of my stuns

**Comment by shirsig** [comment]
now?

**Comment by NibelheimGG** [comment]
seems fixed by now, thank you bro for the fast updates

**Comment by shirsig** [comment]
great, you're welcome :)

**Comment by NibelheimGG** [comment]
the stuns not working in PVP, lua error is fixed but i cant see stun on players only moobs

**Comment by shirsig** [comment]
hm, is it on elysium? might be because of lag

**Comment by NibelheimGG** [comment]
yes im on elysium, i just stunlocked a guy with my rogue and didnt seen any bar, working on moobs

**Comment by shirsig** [comment]
can you try changing the .5 on line 300 of ccwatch.lua to 1 or something? If it works after that it's a lag issue. Elysium had crazy delays for events last time i played there.

**Comment by NibelheimGG** [comment]
i dont feel so much lag, 30ms and the server not lagging at all, i will keep testing

**Comment by NibelheimGG** [comment]
value changed to 1, going to test it again on some gnomes :d

**Comment by NibelheimGG** [comment]
no more problems with dealy at 1
