### ISSUE TITLE
Hamstring is not tracked even tho its in the .lua

### ISSUE THREAD

**Issue by Larsy93** [shirsig/aurae#22]
Any ideas why?

**Comment by shirsig** [comment]
No, works fine for me.

**Comment by Larsy93** [comment]
Weird, mortal strike works fine. Its on Lights Hope/Elysium but that shouldnt make a difference i Guess. Tried deleting everything from My wtf folder but still nothing :/

**Comment by shirsig** [comment]
You can try increasing the delay from .5 seconds on line 26 of the .lua file. If the delay is huge due to overpopulation it may not be applied yet during the check.
