### ISSUE TITLE
Rogue's Kidney Shot is not being tracked

### ISSUE THREAD

**Issue by polischuk16** [shirsig/aurae#26]
For some reason Kidney Shot isn't showing.
Cheap Shot is showing, Gouge is showing, Riposte is showing, but Kidney Shot does not.

**Comment by shirsig** [comment]
should be fixed now

**Comment by polischuk16** [comment]
> should be fixed now

Just updated and tried. Still not working.

**Comment by shirsig** [comment]
now?

**Comment by polischuk16** [comment]
> now?

Working now <3
