### ISSUE TITLE
WoW Classic Issues

### ISSUE THREAD

**Issue by thescreensavers** [shirsig/aurae#27]
Hey First off thanks for working on this mod!

1. /ccwatch does not work I have to type /ccc 
2. Frost Nova is not being tracked. 

Side Comment, it would be nice to have the addon version number somewhere to reference. 

I downloaded this mod using Twitch App.

**Comment by shirsig** [comment]
What about now with the newest version for frost nova?
The addon has been renamed to ccc, hence /ccc. ccwatch was stolen from an old 1.12 addon so I had to change it when I put it on curse.
I'm now adding the version number to the .toc file for all new changes.
