### ISSUE TITLE
Please put it to Twitch

### ISSUE THREAD

**Issue by DavidBabel** [shirsig/aurae#28]
Hey there, 

This is a great addon, for easy distribution and update i strongly suggest you to share it with Twitch addon manager, which is far used by Classic player to maintain their addons.

Thanks to consider, and congratulation for the work

**Comment by shirsig** [comment]
Hey. It is on curse already, is there something else to be done for that? (I haven't played retail in like a decade so I'm not very familiar with the addon ecosystem)
