### ISSUE TITLE
Freezing trap is not being tracked

### ISSUE THREAD

**Issue by Nixxen** [shirsig/aurae#29]
Dropping a freezing trap as a hunter, pulling a mob into it while attacking a second mob, the CCC will not trigger a trap timer.

**Comment by shirsig** [comment]
It should. Could it have been out of combat log range? In that case there is no way for the addon to know.

**Comment by Nixxen** [comment]
Tested a few times now in and out of combat.
It never seems to trigger regardless of range.
I.e. I place a trap, pull a mob into the trap and keep it targeted the whole time, but as the trap triggers there's not any indication on the CCC bars.

**Comment by shirsig** [comment]
Did you try it with the newest version? There have been some freezing trap related fixes.

**Comment by Nixxen** [comment]
Seems like it's working fine now!
Tested in and out of combat, with and without target selected and it's been triggering the timer consistently.
