### ISSUE TITLE
Sap bugged it out

### ISSUE THREAD

**Issue by Axaion** [shirsig/aurae#30]
sapped another rogue with a cleartarget macro, causing it to bug out.

heres what bugsack tells me

ccc\ccc-0.1.6.lua:379: attempt to concatenate local 'unit' (a nil value)
ccc\ccc-0.1.6.lua:379: in function `StartTimer'
ccc\ccc-0.1.6.lua:279: in function <ccc\ccc.lua:275>

Locals:
InCombatSkipped

**Comment by shirsig** [comment]
Should be fixed.
