### ISSUE TITLE
Fixed - LUA Errors

### ISSUE THREAD

**Issue by Scoboose** [shirsig/aurae#31]
When using bartenders "Auto-Assist casting" and casting a tracked CC then targeting the mob the spell was cast on you get the following error and it just keeps counting up rather fast.

Message: Interface\AddOns\ccc\ccc.lua:381: attempt to concatenate local 'unit' (a nil value)
Time: Mon Sep 16 23:26:13 2019
Count: 12894
Stack: Interface\AddOns\ccc\ccc.lua:381: attempt to concatenate local 'unit' (a nil value)
[C]: ?
Interface\AddOns\ccc\ccc.lua:381: in function `StartTimer'
Interface\AddOns\ccc\ccc.lua:281: in function <Interface\AddOns\ccc\ccc.lua:277>

Locals:

**Comment by shirsig** [comment]
Did you test with the newest version? I just fixed a similar bug.

**Comment by Scoboose** [comment]
Seems to be no errors now. Thank you!
