### ISSUE TITLE
Frostbolt timing broken

### ISSUE THREAD

**Issue by WayOfTheRoad** [shirsig/aurae#32]
My rank 9 frostbolt's slow lasts 9 seconds.  CCC shows it as 12 seconds and it messes up further if I reapply the slow in that extra 3 seconds after the first has faded, while it's still counting down.

**Comment by shirsig** [comment]
Strange,, seems like it applies the 3 second talent bonus even though I assume you don't have it? Or is the base duration wrong?

**Comment by WayOfTheRoad** [comment]
Correct, I don't have the talent Permafrost.  The 12 seconds _would_ be correct if I had 3/3 Permafrost.

**Comment by shirsig** [comment]
Ok, I think it's probably looking at the wrong talent for the bonus. Will try to fix it after work.

**Comment by WayOfTheRoad** [comment]
Thank you very much!

**Comment by shirsig** [comment]
I committed the fix. Does it work now? (It's not on curse yet)

**Comment by WayOfTheRoad** [comment]
It is still adding 3 seconds to Frostbolt and Cone of Cold.  They can break and stop tracking altogether if I reapply the slow while the extra 3 seconds is still counting down.  If it doesn't break, it also does not start timing the new application of the the slow -- it will finish counting down the 3 seconds.

**Comment by WayOfTheRoad** [comment]
Also, I can't tell you under which conditions, but Frost Nova fails to track/time sometimes.

**Comment by shirsig** [comment]
Oh, I missed some places. What about now?
For frost nova please open a separate bug.

**Comment by WayOfTheRoad** [comment]
Seems to work now!
