### ISSUE TITLE
Add option to not track abilities 

### ISSUE THREAD

**Issue by seren887** [shirsig/aurae#33]
I love the addon because it is minimalist but it should be more configurable because it is too spammy as a frost mage (constantly tracking all slows and frostbite) Tracking things like frostbolt slow is largely pointless in PvP. 

It would be ideal if it was easier to modify it to only show hard CC  + engineering items like MC cap/rocket helm.

**Comment by shirsig** [comment]
Added an ignore list.
**/ccc ignore _name_** to toggle.
**/ccc ignore** to list.
Must be the debuff name, not the spell name (usually they're the same)
