### ISSUE TITLE
Error matching nil string

### ISSUE THREAD

**Issue by seanrich** [shirsig/aurae#38]
Date: 2019-11-15 16:07:52
ID: 1
Error occured in: Global
Count: 2
Message: ..\AddOns\ccc\ccc.lua line 281:
   bad argument #1 to 'gmatch' (string expected, got nil)
Debug:
   [C]: gmatch()
   ccc\ccc.lua:281: ?()
   ccc\ccc.lua:7:
      ccc\ccc.lua:6
Locals:
(*temporary) = nil
(*temporary) = "(.+) dies"
(*temporary) = "string expected, got nil"

**Comment by shirsig** [comment]
fixed.
