### ISSUE TITLE
Hunter Spells

### ISSUE THREAD

**Issue by Voidmenull** [shirsig/aurae#4]
It seems like aurae doesnt support a single hunter spell...
Concussive Shot, Serpent Sting, Viper Sting, Volley, all Traps etc

**Comment by shirsig** [comment]
Some are definitely supported. I see serpent sting all the time at least. Not the others because I only play 19 pvp but at least viper sting is listed as a debuff so it should work too. Traps will only work in pvp. Volley isn't even a debuff, is it?

**Comment by shirsig** [comment]
Could be that viper and serpent sting also don't work in pve because of the delay, if so that should be fixed now and I've added concussive shot.

**Comment by Voidmenull** [comment]
wing clip still doesnt work (at least in pve)

**Comment by Voidmenull** [comment]
wyvern sting also

**Comment by shirsig** [comment]
Maybe they work now. By the way, do all stings have a delay between cast and application?

**Comment by Voidmenull** [comment]
its super strange, the stings react only when i cast them 2+ times and they react without any delay

**Comment by shirsig** [comment]
are you talking about aurae now? I was talking about game mechanics (fly time of the projectile)

**Comment by Voidmenull** [comment]
ah, yea i was talking about aurea...but the projectile has also a fly-delay, yes

**Comment by Voidmenull** [comment]
seems like it works flawless if im close to a target

**Comment by shirsig** [comment]
yeah, I need to add the fly time for the pve mechanic or it won't be applied. I've made it one second now, guess that's not enough then if you're too far? or are you not using that version yet

**Comment by Voidmenull** [comment]
let me update quick

**Comment by Voidmenull** [comment]
its working only from a rly rly short range, not useable like that :/

**Comment by shirsig** [comment]
the same for all? what's the fly time? It works fine for me for frostbolt and others

**Comment by Voidmenull** [comment]
idk what the fly time is, but def. shorter then on the mage (where it works), its the same for all spells...

**Comment by shirsig** [comment]
Probably now, somehow sting got autocompleted to string (i assume it was already working for concussive shot?)

**Comment by Voidmenull** [comment]
still the same :/ concussive has also only low range :/

**Comment by shirsig** [comment]
the top of your data/actions.lua looks like this? ```aurae_DELAYS = {
	["Fireball"] = 1,
	["Frostbolt"] = 1,
	["Concussive Shot"] = 1,
	["Viper Sting"] = 1,
	["Serpent Sting"] = 1,
	["Wyvern Sting"] = 1,
}```

**Comment by Voidmenull** [comment]
yes ofc :)

**Comment by shirsig** [comment]
no idea then, guess will have to wait till nost brings back my 19 hunter twink to test this xD

**Comment by Voidmenull** [comment]
alright :) maybe its my emulator that doing something wrong (invisible cast time line)

**Comment by Voidmenull** [comment]
the problem is somewhere in the delay calculation line 338:
pending[effect] = {target=target, time=GetTime() + (aurae_RANKS[effect] and aurae_DELAYS[effect] or 0)}

for my mage i get Print(pending[effect].time - GetTime())
1 second, for the hunter 0 seconds...

**Comment by Voidmenull** [comment]
aurae_RANKS[effect] is not a part of actions.lua for the hunter and therefore nil :)

**Comment by shirsig** [comment]
what?

**Comment by Voidmenull** [comment]
the delay from  (aurae_RANKS[effect] and aurae_DELAYS[effect] or 0)
is always 0 because there is no aurae_RANKS[effect] for the hunter shots

**Comment by Voidmenull** [comment]
http://i.imgur.com/5jgr9Ku.png

here an example(for serpent sting) you have to add to make it work...
otherwise line 338 will calculate always GetTime() + 0 seconds as delay:
pending[effect] = {target=target, time=GetTime() + (aurae_RANKS[effect] and aurae_DELAYS[effect] or 0)}
since aurae_RANKS[effect] is nil

**Comment by shirsig** [comment]
Ah yeah that conditional was an artifact from when delay was a field in the ranks entries that i forgot to remove. Now it should work, thanks.

**Comment by Voidmenull** [comment]
fixed, ty :)
