### ISSUE TITLE
[Bug] Error when reaplying debuff on same target.

### ISSUE THREAD

**Issue by Theryk** [shirsig/aurae#7]
Interface\AddOns\aurae\aurae.lua:336: attempt to perform arithmetic on field '?' (a nil value)

**Comment by shirsig** [comment]
thanks, fixed

**Comment by Theryk** [comment]
still bugged :\

**Comment by shirsig** [comment]
hm, not for me. sure you updated properly? when does it happen?

**Comment by Theryk** [comment]
nevermind, its fixed, my bad :( sorry

**Comment by shirsig** [comment]
No problem :) good night
