### ISSUE TITLE
Error and Spells

### ISSUE THREAD

**Issue by Voidmenull** [shirsig/aurae#8]
the line 336 gives an error for non-delay users:
pending[effect] = {target=target, time=GetTime() + aurae_DELAYS[effect] or 0}

this can be fixed by useing brackets for the "or"
pending[effect] = {target=target, time=GetTime() + (aurae_DELAYS[effect] or 0)}

Spells:

Hunters missing scorpid sting
Rogues missing exposed armor + the rapture timer is wrong independent from used rank

hope you can fix this :)

**Comment by shirsig** [comment]
The precedence bug I fixed last night already. As for scorpid sting/exposed armor, they're not really missing, just like probably quite many spells not tracked because they didn't seem important enough. But there's no harm in adding them I guess.

**Comment by Voidmenull** [comment]
i guess you cant add hunter traps? seems like its not possible to determinate the trap caster?

**Comment by shirsig** [comment]
In pvp (combat log events) they work. The caster can't be detected that way but the real problem for pve is that the target can't be detected. Like I said in the PMs a while ago this is not as big an issue if you need the timers for the current target only so you could use the pvp mechanic for pve too.

**Comment by Voidmenull** [comment]
any updates with the spells?

**Comment by shirsig** [comment]
Only that I added scorpid sting.

**Comment by shirsig** [comment]
I've changed the pvp tracking to only include the player's own spells now. It uses the same mechanic as pvp with a minor change so that it doesn't have a delay.

I've also made a branch "target" with what I think would be the best tracking (combat log for pvp and pve) for target only as you're using it. (Well, it may not even work, I can't test it well because there are no bars included, but, you know, in principle.)

**Comment by Voidmenull** [comment]
ty, i will check that out :) what about the rapture timers? you took a look on that?

**Comment by shirsig** [comment]
rupture* should be fixed

**Comment by Voidmenull** [comment]
nice :D

**Comment by shirsig** [comment]
I also removed the bars from that version. I would suggest you rename it and the handful of globals (which all start in "aurae") so they can run side by side

**Comment by Voidmenull** [comment]
thats a good idea, i will do this! ty for your effort!
