### ISSUE TITLE
aurae bars

### ISSUE THREAD

**Issue by surpr** [shirsig/aurae#9]
You can do-canceling diminishing returns, and filter to display only stuns? I need this addon instead Stunwatch. And still a good idea to make changes not only the scale but also the length of the bars. Thank you.

**Comment by shirsig** [comment]
The newest version only displays CCs and a small number of other effects (none for rogues) and only the player's own spells so for rogues it actually will only show stuns. You can't remove the diminishing returns but why would you? they're very important, especially for stuns.

If you want to change the look you'll have to edit the code yourself, sorry. I'll never add customization for that.
